apiVersion: v1
kind: Pod
metadata: name:dbpod
spec:
  containers:
    - images: mysql:5.7
      name: mysql
      volumeMounts:
        - mountPath: /var/lib/mysql
            name:dbvol
  volumes:
    - name: dbvol
      hostPath:
        path: /data
          type:DirectoryOrCreate
